### ISSUE TITLE
L1 and L2 values

### ISSUE THREAD

**Issue by Hamza3226** [ShallMate/FastECDLP#1]
Where should I change the value for L1 and L2? I want to generate results for Table IV given in the paper

**Comment by ShallMate** [comment]
Please check lines 17 to 25 of ciphering.go for the answers you need

**Comment by Hamza3226** [comment]
Hi, I am doing it but it is giving me errors
I changed 	Ilen      = 11  and	Jlen      = 25 for testing but it is giving me error

**Comment by Hamza3226** [comment]
can you suggest some values so that it does not give memory errors, I am running it on my PC with 8gb ram

**Comment by ShallMate** [comment]
Because the program that generates tables takes up a lot of memory, but the generated tables are actually not that large. If you are on a PC with 8GB RAM, my suggestion is to reduce the size of L1.

**Comment by Hamza3226** [comment]
Also, for T=2,4,16 I need to change the value for Threadnum, right??

**Comment by ShallMate** [comment]
That's true

**Comment by Hamza3226** [comment]
Thanks for the information, I will try to implement it using these suggestions and will get back to you if it works.

**Comment by ShallMate** [comment]
Okay, good luck to you
