### ISSUE TITLE
Generating T1

### ISSUE THREAD

**Issue by Hamza3226** [ShallMate/FastECDLP#2]
const (
	Ilen      = 10   // l2-1
	Imax      = 1024 // 1<< Ilen
	Treelen   = 2048 // imax*2
	TestNum   = 1000
	Jlen      = 24       // l1-1
	Jmax      = 16777216 // 1<<Jlen
	cuckoolen = 21810381 //jmax*1.3
)

Hi, I am replacing Jlen =20, but it still gives me an error. Also, do I need to adjust the values of Jmax and Cuckoolen also?

if yes, how should I adjust those values? can you please suggest to me some values I should try ??

**Comment by ShallMate** [comment]
No, it is not necessary. I tried the parameter of Jlen=24 in my local. I think it is completely able to generate the table under 8GB RAM, let alone Jlen=20. It doesn't seem to be a memory issue, can you give me a screenshot of the error? Or tell me in more detail what went error?

**Comment by Hamza3226** [comment]
Hi, when I changed the value to 20, it is giving me this error:

fatal error: out of memory

**Comment by Hamza3226** [comment]
It is not able to allocate more memory in Panic.go file which is an internal library of go

**Comment by Hamza3226** [comment]
![Screenshot 2023-08-13 130616](https://github.com/ShallMate/FastECDLP/assets/48592137/63b31e01-8283-448b-9cf2-9f1a9c567f4a)

**Comment by Hamza3226** [comment]
HI, I have one question. how did you used this in FL??
Did you implemented the FL settings in C++??

**Comment by ShallMate** [comment]
Yes. Indeed, in our practical production environment (while collaborating with Sudo Company), we utilize a FastECDLP implementation and a federated learning framework developed in the C++ programming language. Due to the confidentiality requirements of our company's code, we are presenting here a FastECDLP version in the Go programming language. Through our testing, the performance of these two versions is quite comparable.

**Comment by Hamza3226** [comment]
Hello, I have a question. In what file did you apply Montgomery's trick?
I am new to Cryptography and am learning Cyber security and cryptography that's why. Sorry if it is a silly/basic question.
Thank you

**Comment by ShallMate** [comment]
Please refer to lines 71 to 111 under the ciphering.go file.

**Comment by Hamza3226** [comment]
Hi, I am confused why you gave 3 encrypt func in the ciphering go i.e., 

func Encrypt(pubkey *PublicKey, m *big.Int) *Cipher {
	start1 := time.Now()
	r, _ := NewPrivateKey(c)
	rpkx, rpky := c.ScalarMult(pubkey.X, pubkey.Y, r.D.Bytes())
	cost1 := time.Since(start1)
	//fmt.Printf("btcecc encrypt cost=[%s]\n", cost1)
	GetEnc = GetEnc + cost1
	mGx, mGy := c.ScalarBaseMult(m.Bytes())
	//fmt.Println(mGx)
	if m.Cmp(zero) == -1 {
		mGy = mGy.Sub(c.P, mGy)
	}
	c2x, c2y := c.Add(mGx, mGy, rpkx, rpky)
	return &Cipher{r.PublicKey.X, r.PublicKey.Y, c2x, c2y}
}

func NormalEnc(pubkey *PublicKey, m *big.Int) *Cipher {
	start1 := time.Now()
	r, _ := NewPrivateKey(c)
	rpkx, rpky := c.ScalarMult(pubkey.X, pubkey.Y, r.D.Bytes())
	cost1 := time.Since(start1)
	//fmt.Printf("btcecc encrypt cost=[%s]\n", cost1)
	GetEnc = GetEnc + cost1
	mGx, mGy := c.ScalarBaseMult(m.Bytes())
	c2x, c2y := c.Add(mGx, mGy, rpkx, rpky)
	return &Cipher{r.PublicKey.X, r.PublicKey.Y, c2x, c2y}
}

func EncryptJob(pubkey *PublicKey, m *big.Int) *FieldCipher {
	r, _ := NewPrivateKey(c)
	rpkx, rpky := c.ScalarMult(pubkey.X, pubkey.Y, r.D.Bytes())
	mGx, mGy := c.ScalarBaseMult(m.Bytes())
	if m.Cmp(zero) == -1 {
		mGy = mGy.Sub(c.P, mGy)
	}
	c2x, c2y, c2z := c.Add1(mGx, mGy, rpkx, rpky)
	c1x, c1y := c.bigAffineToField(r.PublicKey.X, r.PublicKey.Y)
	c1z := new(FieldVal).SetInt(1)
	return &FieldCipher{c1x, c1y, c1z, c2x, c2y, c2z}

**Comment by ShallMate** [comment]
@Hamza3226  Please use the first Enc function, and the second is a general Exp-Elgamal encryption function, so it is named NormalEnc because the original Exp-Elgamal does not support encrypting negative numbers. The third encryption function is encryption in Jacobian coordinates. The Jacobian coordinate is a coordinate form that we wanted to use during the FastECDLP process, which was later discarded.

**Comment by Hamza3226** [comment]
Thanks for the reply.
So, I just need to comment out the 2nd and 3rd encrypt func??

**Comment by Hamza3226** [comment]
HI, in the decryption part you are finding Pm I am confused from where this Pm value is coming as to calculate m = logG Pm we need the value of Pm.
